# Generated by Django 3.2.6 on 2021-08-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20210813_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heading1',
            field=models.TextField(default='There Is not Heading 1 So click on Continue Reading...', max_length=900),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading2',
            field=models.TextField(default='There Is not Heading 2 So click on Continue Reading...', max_length=900),
        ),
    ]
