# Generated by Django 3.1.7 on 2021-08-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20210813_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo1',
            field=models.ImageField(default='', upload_to='Images/'),
            preserve_default=False,
        ),
    ]
