# Generated by Django 3.1.7 on 2021-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_post_photo1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=models.ImageField(upload_to='static/Images/'),
        ),
    ]
