# Generated by Django 3.1.7 on 2021-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210814_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo2',
            field=models.ImageField(default='', upload_to='static/Images/'),
            preserve_default=False,
        ),
    ]
