# Generated by Django 3.1.7 on 2021-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=500000),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo1',
            field=models.ImageField(default='http://placehold.it/200x200', upload_to='static/Images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo2',
            field=models.ImageField(default='http://placehold.it/200x200', upload_to='static/Images/'),
        ),
    ]
