# Generated by Django 3.1.7 on 2021-08-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20210814_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Facebook_id',
            field=models.TextField(default='https://facebook.com/thechandrapalsinghrajput', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='Instagram_id',
            field=models.TextField(default='https://instagram.com/thechandrapalsinghrajput', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='twitter_id',
            field=models.TextField(default='https://twitter.com/thechandrapalsinghrajput', max_length=100),
        ),
    ]
