# Generated by Django 3.1.7 on 2021-08-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210814_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heading2',
            field=models.TextField(max_length=900),
        ),
    ]
