# Generated by Django 3.1.7 on 2021-08-16 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_auto_20210816_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messages',
            new_name='message',
        ),
    ]
