# Generated by Django 3.1.7 on 2021-08-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20210816_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='heading1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='heading2',
        ),
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.TextField(default='Heading contain only 110 word', max_length=110),
        ),
        migrations.AddField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(default='https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg', upload_to='images/'),
        ),
    ]
