# Generated by Django 3.1.7 on 2021-08-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp']},
        ),
    ]
